[project]
name = "113502513-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "capybara", email = "hgfhyk50702@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
113502513-exercise = "113502513_exercise:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
